#!/usr/bin/env node
/**
 * pnpm setup — Project initialization wizard for the Custom Design System.
 *
 * Asks 6 questions, then:
 *   1. Injects a custom brand scale into tokens.css (if custom hex was chosen)
 *   2. Writes project.config.json
 *   3. Updates the ## Project Config section in CLAUDE.md
 *   4. Generates a pre-configured index.html starter
 */

import readline from 'readline';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

// ─── Brand hues defined in tokens.css ────────────────────────────────────────

const BRANDS = [
  { name: 'indigo',   hex: '#6366f1' },
  { name: 'violet',   hex: '#8b5cf6' },
  { name: 'fuchsia',  hex: '#d946ef' },
  { name: 'pink',     hex: '#ec4899' },
  { name: 'rose',     hex: '#f43f5e' },
  { name: 'red',      hex: '#ef4444' },
  { name: 'orange',   hex: '#f97316' },
  { name: 'amber',    hex: '#f59e0b' },
  { name: 'emerald',  hex: '#10b981' },
  { name: 'teal',     hex: '#14b8a6' },
  { name: 'cyan',     hex: '#06b6d4' },
  { name: 'blue',     hex: '#3b82f6' },
];

const STYLES = [
  { name: 'standard',   font: 'Inter',          desc: 'New product, modern SaaS, safest modern web feel' },
  { name: 'enterprise', font: 'IBM Plex Sans',   desc: 'Formal B2B, conservative, compliance-heavy' },
  { name: 'friendly',   font: 'DM Sans',         desc: 'Consumer SaaS, SMB, education, warmer brand' },
  { name: 'refined',    font: 'Geist',           desc: 'Premium, design-led, craft matters' },
  { name: 'data-dense', font: 'Inter (tabular)', desc: 'Power tools, analytics, observability, dashboards' },
];

const SIZES = [
  { name: 'xs', desc: 'Extra compact — tight tables, dense toolbars' },
  { name: 'sm', desc: 'Compact — secondary actions, sidebar items' },
  { name: 'md', desc: 'Default — forms, page actions (recommended)' },
  { name: 'lg', desc: 'Spacious — landing CTAs, empty states' },
];

// ─── Readline helpers ─────────────────────────────────────────────────────────

function ask(rl, question) {
  return new Promise(resolve => rl.question(question, answer => resolve(answer.trim())));
}

function pickFromList(answer, list, defaultIndex = 0) {
  const n = parseInt(answer, 10);
  if (isNaN(n) || n < 1 || n > list.length) return list[defaultIndex];
  return list[n - 1];
}

// ─── Custom color scale generator ────────────────────────────────────────────

function hexToRgb(hex) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!result) return null;
  return { r: parseInt(result[1], 16), g: parseInt(result[2], 16), b: parseInt(result[3], 16) };
}

function rgbToHsl(r, g, b) {
  r /= 255; g /= 255; b /= 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  let h = 0, s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = (g - b) / d + (g < b ? 6 : 0); break;
      case g: h = (b - r) / d + 2; break;
      case b: h = (r - g) / d + 4; break;
    }
    h /= 6;
  }
  return { h: Math.round(h * 360), s: Math.round(s * 100), l: Math.round(l * 100) };
}

function hslToHex(h, s, l) {
  s /= 100; l /= 100;
  const a = s * Math.min(l, 1 - l);
  const f = n => {
    const k = (n + h / 30) % 12;
    const color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1);
    return Math.round(255 * color).toString(16).padStart(2, '0');
  };
  return `#${f(0)}${f(8)}${f(4)}`;
}

// Generates a 10-stop perceptual scale from a single hex value.
// Stops: 50 100 200 300 400 500 600 700 800 900
function generateScale(hex) {
  const rgb = hexToRgb(hex);
  if (!rgb) return null;
  const { h, s } = rgbToHsl(rgb.r, rgb.g, rgb.b);

  const stops = [
    { stop: 50,  l: 97, sMult: 0.25 },
    { stop: 100, l: 93, sMult: 0.35 },
    { stop: 200, l: 85, sMult: 0.55 },
    { stop: 300, l: 75, sMult: 0.75 },
    { stop: 400, l: 63, sMult: 0.90 },
    { stop: 500, l: 50, sMult: 1.00 },
    { stop: 600, l: 41, sMult: 0.95 },
    { stop: 700, l: 33, sMult: 0.90 },
    { stop: 800, l: 26, sMult: 0.80 },
    { stop: 900, l: 18, sMult: 0.65 },
  ];

  return stops.map(({ stop, l, sMult }) => ({
    stop,
    hex: hslToHex(h, Math.round(s * sMult), l),
  }));
}

function injectCustomBrand(hueName, scale) {
  const tokenPath = path.join(ROOT, 'src/whitelabel/tokens.css');
  let css = fs.readFileSync(tokenPath, 'utf8');

  const rootVars = scale.map(({ stop, hex }) => `  --${hueName}-${stop}: ${hex};`).join('\n');
  const brandAlias = scale.map(({ stop }) =>
    `--brand-${stop}:var(--${hueName}-${stop})`).join(';');

  const block =
    `/* CUSTOM BRAND: ${hueName} — generated by pnpm setup */\n` +
    `:root {\n${rootVars}\n}\n` +
    `:root[data-brand="${hueName}"] { ${brandAlias}; }\n` +
    `/* END CUSTOM BRAND: ${hueName} */`;

  // Replace existing block for this name (idempotent)
  const re = new RegExp(
    `/\\* CUSTOM BRAND: ${hueName}[\\s\\S]*?/\\* END CUSTOM BRAND: ${hueName} \\*/\\n?`,
    'g'
  );
  css = css.replace(re, '');
  css = css.trimEnd() + '\n\n' + block + '\n';
  fs.writeFileSync(tokenPath, css);
}

// ─── Output file writers ──────────────────────────────────────────────────────

function writeConfig(config) {
  fs.writeFileSync(
    path.join(ROOT, 'project.config.json'),
    JSON.stringify(config, null, 2) + '\n'
  );
}

function updateClaudeMd(config) {
  const claudePath = path.join(ROOT, 'CLAUDE.md');
  let content = fs.readFileSync(claudePath, 'utf8');

  const styleInfo = STYLES.find(s => s.name === config.style);
  const font = config.font || (styleInfo ? styleInfo.font : 'Inter');

  const section =
    `## Project Config\n` +
    `<!-- generated by \`pnpm setup\` — re-run to change -->\n\n` +
    `| Setting | Value |\n` +
    `|---|---|\n` +
    `| Name | ${config.name} |\n` +
    `| Brand | ${config.brand} |\n` +
    `| Style | ${config.style} |\n` +
    `| Theme | ${config.theme} |\n` +
    `| Default size | ${config.size} |\n` +
    `| Font | ${font} |\n\n` +
    `**Binding rules for Claude Code:**\n` +
    `- \`<html>\` must always carry \`data-brand="${config.brand}"\` \`data-style="${config.style}"\` \`data-theme="${config.theme}"\`\n` +
    `- Default component size is \`${config.size}\` — override only when context requires (table headers → \`xs\`/\`sm\`, landing CTAs → \`lg\`)\n` +
    `- Only use components from \`src/whitelabel/\` — never invent new components\n` +
    `- Never reference a raw color scale — only semantic tokens (\`--fg-*\`, \`--bg-*\`, \`--border-*\`, \`--space-*\`)\n` +
    `- One brand, one accent — a second color must come from the status set (success/warning/danger/info)\n` +
    `- Font: ${font}${config.font ? ` (overridden from ${styleInfo?.font})` : ' (set by style preset)'}\n`;

  // Replace existing section (idempotent) or append
  const re = /## Project Config\n[\s\S]*?(?=\n## (?!Project Config)|\n---\s*\n|$)/;
  if (re.test(content)) {
    content = content.replace(re, section.trimEnd());
  } else {
    content = content.trimEnd() + '\n\n' + section;
  }

  fs.writeFileSync(claudePath, content);
}

function generateStarterHtml(config) {
  const styleInfo = STYLES.find(s => s.name === config.style);
  const font = config.font || (styleInfo ? styleInfo.font : 'Inter');

  return `<!doctype html>
<html lang="en" data-theme="${config.theme}" data-brand="${config.brand}" data-style="${config.style}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${config.name}</title>
  <link rel="stylesheet" href="src/whitelabel/tokens.css" />
  <script src="https://unpkg.com/react@18.3.1/umd/react.development.js" integrity="sha384-hD6/rw4ppMLGNu3tX5cjIb+uRZ7UkRJ6BPkLpg4hAu/6onKUg4lLsHAs9EBPT82L" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/react-dom@18.3.1/umd/react-dom.development.js" integrity="sha384-u6aeetuaXnQ38mYT8rp6sbXaQe3NL9t+IBXmnYxwkUI2Hw4bsp2Wvmx4yRQF1uAm" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/@babel/standalone@7.29.0/babel.min.js" integrity="sha384-m08KidiNqLdpJqLq95G/LEi8Qvjl/xUYll3QILypMoQ65QorJ9Lvtp2RXYGBFj1y" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/lucide@latest"></script>
</head>
<body>
  <div id="root"></div>

  <!-- Load only the component files you need for this screen -->
  <script type="text/babel" src="src/whitelabel/Primitives.jsx"></script>

  <script type="text/babel">
    const { Button, Card, Alert, Typography } = window;

    function App() {
      return (
        <div style={{ padding: 'var(--space-7)', maxWidth: 640, margin: '0 auto' }}>
          <Typography variant="h1" style={{ marginBottom: 'var(--space-4)' }}>
            ${config.name}
          </Typography>
          <Alert variant="info" title="Ready to build">
            Brand: ${config.brand} · Style: ${config.style} · Theme: ${config.theme} · Size: ${config.size} · Font: ${font}
          </Alert>
        </div>
      );
    }

    ReactDOM.createRoot(document.getElementById("root")).render(<App />);
  </script>
</body>
</html>
`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  const bold  = s => `\x1b[1m${s}\x1b[0m`;
  const cyan  = s => `\x1b[36m${s}\x1b[0m`;
  const green = s => `\x1b[32m${s}\x1b[0m`;
  const dim   = s => `\x1b[2m${s}\x1b[0m`;

  console.log(`\n${bold(cyan('Custom Design System — Project Setup'))}\n`);
  console.log('Answers get written to project.config.json and CLAUDE.md.');
  console.log('Claude Code reads CLAUDE.md automatically — your choices become binding rules.\n');

  // ── 1. Project name ──────────────────────────────────────────────────────────
  const name = (await ask(rl, `${bold('1.')} Project name: `)) || 'My Project';

  // ── 2. Brand ─────────────────────────────────────────────────────────────────
  console.log(`\n${bold('2.')} Brand hue:`);
  BRANDS.forEach((b, i) =>
    console.log(`   ${String(i + 1).padStart(2)}.  ${b.name.padEnd(10)}  ${dim(b.hex)}`)
  );
  console.log(`   ${String(BRANDS.length + 1).padStart(2)}.  ${dim('Custom hex color')}`)
  const brandChoice = await ask(rl, `   Choose [1-${BRANDS.length + 1}, default 1]: `);

  let brand, customHueName;
  const brandN = parseInt(brandChoice, 10);
  if (brandN === BRANDS.length + 1) {
    const rawHex = await ask(rl, '   Hex value (e.g. #3a7bd5): ');
    customHueName = (await ask(rl, '   Name for this hue (lowercase, no spaces, e.g. ocean): '))
      .toLowerCase().replace(/[^a-z0-9-]/g, '-') || 'custom';
    brand = customHueName;
    // Validate + generate scale later
    const scale = generateScale(rawHex);
    if (!scale) {
      console.log(`   ${dim('Invalid hex — falling back to indigo')}`);
      brand = 'indigo';
      customHueName = null;
    } else {
      console.log(`   Generating scale for ${bold(customHueName)}...`);
      injectCustomBrand(customHueName, scale);
      console.log(`   ✓ Added to src/whitelabel/tokens.css`);
    }
  } else {
    brand = (pickFromList(brandChoice, BRANDS, 0)).name;
  }

  // ── 3. Style preset ──────────────────────────────────────────────────────────
  console.log(`\n${bold('3.')} Style preset:`);
  STYLES.forEach((s, i) =>
    console.log(`   ${i + 1}.  ${s.name.padEnd(12)}  ${s.font.padEnd(20)}  ${dim(s.desc)}`)
  );
  const styleChoice = await ask(rl, '   Choose [1-5, default 1]: ');
  const style = (pickFromList(styleChoice, STYLES, 0)).name;

  // ── 4. Default theme ─────────────────────────────────────────────────────────
  console.log(`\n${bold('4.')} Default theme:`);
  console.log('   1.  light  (recommended — dark is always available at runtime)');
  console.log('   2.  dark');
  const themeChoice = await ask(rl, '   Choose [1-2, default 1]: ');
  const theme = themeChoice === '2' ? 'dark' : 'light';

  // ── 5. Default component size ─────────────────────────────────────────────────
  console.log(`\n${bold('5.')} Default component size:`);
  SIZES.forEach((s, i) =>
    console.log(`   ${i + 1}.  ${s.name.padEnd(4)}  ${dim(s.desc)}`)
  );
  const sizeChoice = await ask(rl, '   Choose [1-4, default 3 = md]: ');
  const size = (pickFromList(sizeChoice, SIZES, 2)).name;

  // ── 6. Font override ──────────────────────────────────────────────────────────
  const styleInfo = STYLES.find(s => s.name === style);
  const presetFont = styleInfo ? styleInfo.font.replace(' (tabular)', '') : 'Inter';
  console.log(`\n${bold('6.')} Font — the ${bold(style)} preset uses ${bold(presetFont)} by default.`);
  console.log('   1.  Use preset default  (recommended)');
  console.log('   2.  Inter');
  console.log('   3.  IBM Plex Sans');
  console.log('   4.  DM Sans');
  console.log('   5.  Geist');
  const fontChoice = await ask(rl, '   Choose [1-5, default 1]: ');
  const fontMap = { '2': 'Inter', '3': 'IBM Plex Sans', '4': 'DM Sans', '5': 'Geist' };
  const font = fontMap[fontChoice] || null;

  rl.close();

  // ── Write outputs ─────────────────────────────────────────────────────────────
  const config = { name, brand, style, theme, size, font };

  console.log('');
  process.stdout.write('→ Writing project.config.json... ');
  writeConfig(config);
  console.log('✓');

  process.stdout.write('→ Updating CLAUDE.md...          ');
  updateClaudeMd(config);
  console.log('✓');

  process.stdout.write('→ Generating index.html...       ');
  fs.writeFileSync(path.join(ROOT, 'index.html'), generateStarterHtml(config));
  console.log('✓');

  const resolvedFont = font || presetFont;
  console.log(`\n${bold(green('✓ Setup complete!'))}\n`);
  console.log(`  Project : ${bold(name)}`);
  console.log(`  Brand   : ${brand}`);
  console.log(`  Style   : ${style}`);
  console.log(`  Theme   : ${theme}`);
  console.log(`  Size    : ${size}`);
  console.log(`  Font    : ${resolvedFont}`);
  console.log('');
  console.log('Next steps:');
  console.log('  1. Open index.html in a browser to verify the look.');
  console.log('  2. Run  claude  to start Claude Code — it reads CLAUDE.md automatically.');
  console.log('  3. Re-run  pnpm setup  at any time to change the config.\n');
}

main().catch(err => {
  console.error('\nSetup failed:', err.message);
  process.exit(1);
});
